// <auto-generated />
namespace Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class bigger_seed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bigger_seed));
        
        string IMigrationMetadata.Id
        {
            get { return "202102011251031_bigger_seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
